/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package thehotelfinder.frames;

import thehotelfinder.databaseutil.Hotel;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JComponent;

/**
 *
 * @author Rohith
 */
public class HotelFrame extends javax.swing.JFrame {
    
    /**
     * Creates new form HotelFrame
     */
    public HotelFrame(Hotel hotel) {
        this.hotel = hotel;
        initComponents();
        hotelNameLabel.setText(hotel.getName());
        locationLabel.setText(hotel.getCity() + ", " + hotel.getState());
        amenitiesLabel.setText(getStringArr(hotel.getHotelDetails()));
        
        if(hotel.getName().equals("Mercure Hyderabad KCP") || hotel.getName().equals("TRANSIT HOTEL") || hotel.getName().equals("HOTEL LE ROI DELHI") || 
           hotel.getName().equals("PARK PRIME KOLKATA") || hotel.getName().equals("FORTUNE SELECT TRINITY")){
            System.out.println("hotel1");
            hotelImageLabel.setIcon(new ImageIcon(getClass().getResource("..\\imgs\\hotel1.jpg")));
        }else if(hotel.getName().equals("Ellala Gachibowli Hyderabad") || hotel.getName().equals("DRAGON FLY") || hotel.getName().equals("CASPIA HOTEL") || 
                 hotel.getName().equals("THE LINDSAY") || hotel.getName().equals("GOLDFINCH HOTELS")){
            hotelImageLabel.setIcon(new ImageIcon(getClass().getResource("..\\imgs\\hotel2.jpg")));
        }else if(hotel.getName().equals("The Park") || hotel.getName().equals("KOHINOOR CONTINENTAL") || hotel.getName().equals("HOTEL SOUTHERN") || 
                 hotel.getName().equals("HOTEL HINDUSTHAN INTERNATIONAL") || hotel.getName().equals("CHANCERY PAVILION")){
            hotelImageLabel.setIcon(new ImageIcon(getClass().getResource("..\\imgs\\hotel3.jpg")));
        }else if(hotel.getName().equals("IBIS Hyderabad Hitec City") || hotel.getName().equals("KEYS SELECT HOTEL NESTOR") || hotel.getName().equals("GINGER DELHI RYN") || 
                 hotel.getName().equals("THE PEERLESS INN KOLKATA") || hotel.getName().equals("ADARSH HAMILTON")){
            hotelImageLabel.setIcon(new ImageIcon(getClass().getResource("..\\imgs\\hotel4.jpg")));
        }else if(hotel.getName().equals("Royalton Hotel") || hotel.getName().equals("T2 BEACON MUMBAI") || hotel.getName().equals("ORANA HOTELS AND RESORTS") || 
                 hotel.getName().equals("Aauris") || hotel.getName().equals("CHANCERY PAVILION")){
            hotelImageLabel.setIcon(new ImageIcon(getClass().getResource("..\\imgs\\hotel5.jpg")));
        }
        
        
        double rating = hotel.getAvgRating();
        ratingWidth = (int)((rating/5)*165);
        System.out.println(rating + " " + ratingWidth);
//        ratingWidth += 10*(((int)rating));
        
        starsBgPanel.setBounds(0, 0, ratingWidth, 30);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HotelPanel = new javax.swing.JPanel();
        hotelNameLabel = new javax.swing.JLabel();
        locationLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        amenitiesLabel = new javax.swing.JLabel();
        ratingPanel = new javax.swing.JPanel();
        stars = new javax.swing.JLabel();
        starsBgPanel = new javax.swing.JPanel();
        hotelImageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(710, 100, 0, 0));
        setSize(new java.awt.Dimension(500, 600));
        getContentPane().setLayout(new java.awt.CardLayout());

        HotelPanel.setBackground(new java.awt.Color(254, 249, 243));
        HotelPanel.setPreferredSize(new java.awt.Dimension(500, 600));
        HotelPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hotelNameLabel.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 32)); // NOI18N
        hotelNameLabel.setText("Hotel Name");
        HotelPanel.add(hotelNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, -1, -1));

        locationLabel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 13)); // NOI18N
        locationLabel.setText("location");
        HotelPanel.add(locationLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        jLabel3.setText("Special facilities:");
        HotelPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 234, -1, -1));

        amenitiesLabel.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        amenitiesLabel.setForeground(new java.awt.Color(102, 102, 102));
        amenitiesLabel.setText("<html> -  one<br> - two<br> - three<br>- four<br>- five</html>");
        HotelPanel.add(amenitiesLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        ratingPanel.setLayout(null);

        stars.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thehotelfinder/imgs/stars.png"))); // NOI18N
        ratingPanel.add(stars);
        stars.setBounds(0, 0, 165, 30);

        starsBgPanel.setBackground(new java.awt.Color(255, 204, 0));

        javax.swing.GroupLayout starsBgPanelLayout = new javax.swing.GroupLayout(starsBgPanel);
        starsBgPanel.setLayout(starsBgPanelLayout);
        starsBgPanelLayout.setHorizontalGroup(
            starsBgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        starsBgPanelLayout.setVerticalGroup(
            starsBgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        ratingPanel.add(starsBgPanel);
        starsBgPanel.setBounds(0, 0, 0, 30);

        HotelPanel.add(ratingPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 160, 30));

        hotelImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thehotelfinder/imgs/hotel1.jpg"))); // NOI18N
        HotelPanel.add(hotelImageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 200, 140));

        getContentPane().add(HotelPanel, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private String getStringArr(ArrayList arr){
        String res = "<html>";
        for(Object s:arr){
            res+=  "• " + (String)s +"<br>";
        }
        res+="</html>";
        return res;
    }

    private Hotel hotel;
    private int ratingWidth;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel HotelPanel;
    private javax.swing.JLabel amenitiesLabel;
    private javax.swing.JLabel hotelImageLabel;
    private javax.swing.JLabel hotelNameLabel;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel locationLabel;
    private javax.swing.JPanel ratingPanel;
    private javax.swing.JLabel stars;
    private javax.swing.JPanel starsBgPanel;
    // End of variables declaration//GEN-END:variables
}
