/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package thehotelfinder.frames;

import java.util.ArrayList;
import javax.swing.JComponent;
import thehotelfinder.TheHotelFinder;

/**
 *
 * @author Rohith
 */
public class MyBookingsFrame extends javax.swing.JFrame {

    /**
     * Creates new form MyBookingsFrame
     */
    public MyBookingsFrame() {
        initComponents();
        bookingCardList = TheHotelFinder.getDb().getBookings(TheHotelFinder.getCurUser().getUsername());
        if(bookingCardList.isEmpty()){
            infoLabel.setText("There are no bookings under your account.");
            return;
        }
        int n = bookingCardList.size();
        int numNotCheckedIn = 0;
        for(int i=0; i<n; i++){
            String s = ((MyBookingCard)bookingCardList.get(i)).getStatus();
            if(s.equals("NOT CHECKED IN")){
                numNotCheckedIn+=1;
            }
        }
        infoLabel.setText("You have " + numNotCheckedIn + " booking(s) NOT checked in");

        for(int i=0; i<bookingCardList.size(); i++){
           scrollPanePanel.add((MyBookingCard)bookingCardList.get(i));
        }

        ((JComponent)getContentPane()).revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MyBookingsPanel = new javax.swing.JPanel();
        jScrollPane = new javax.swing.JScrollPane();
        scrollPanePanel = new javax.swing.JPanel();
        infoLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(510, 140, 900, 800));
        setSize(new java.awt.Dimension(900, 800));
        getContentPane().setLayout(new java.awt.CardLayout());

        MyBookingsPanel.setBackground(new java.awt.Color(254, 249, 243));
        MyBookingsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "My Bookings", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Semibold", 0, 24), new java.awt.Color(0, 102, 255))); // NOI18N
        MyBookingsPanel.setPreferredSize(new java.awt.Dimension(900, 800));
        MyBookingsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        scrollPanePanel.setBackground(new java.awt.Color(254, 249, 243));
        scrollPanePanel.setLayout(new java.awt.GridLayout(25, 0, 0, 25));
        jScrollPane.setViewportView(scrollPanePanel);

        MyBookingsPanel.add(jScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 900, 600));

        infoLabel.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        infoLabel.setForeground(new java.awt.Color(102, 102, 102));
        infoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MyBookingsPanel.add(infoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, -1, -1));

        getContentPane().add(MyBookingsPanel, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents


    ArrayList bookingCardList;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MyBookingsPanel;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JPanel scrollPanePanel;
    // End of variables declaration//GEN-END:variables
}
