/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package thehotelfinder.frames;

import thehotelfinder.TheHotelFinder;

/**
 *
 * @author Rohith
 */
public class MyProfileFrame extends javax.swing.JFrame {

    /**
     * Creates new form MyAccountFrame
     */
    public MyProfileFrame() {
        initComponents();
        nameLabel.setText(TheHotelFinder.getCurUser().getName());
        dobLabel.setText(TheHotelFinder.getCurUser().getDob());
        addressLabel.setText(TheHotelFinder.getCurUser().getAddress()[0] +  ", " + 
                             TheHotelFinder.getCurUser().getAddress()[1] + ", " +
                             TheHotelFinder.getCurUser().getAddress()[2]
                             );
        usernameLabel.setText(TheHotelFinder.getCurUser().getUsername());
        emailLabel.setText(TheHotelFinder.getCurUser().getEmail());
        String asters = "";
        for(int i=0; i<TheHotelFinder.getCurUser().getPassword().length(); i++){
            asters+="*";
        }
        passwordLabel.setText(asters);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane = new javax.swing.JOptionPane();
        MyAccountPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dobLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        passwordToggleBtn = new javax.swing.JToggleButton();
        jLabel8 = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(660, 140, 0, 0));
        setResizable(false);
        setSize(new java.awt.Dimension(600, 600));
        getContentPane().setLayout(new java.awt.CardLayout());

        MyAccountPanel.setBackground(new java.awt.Color(254, 249, 243));
        MyAccountPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "My Account", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Orator Std", 0, 24))); // NOI18N
        MyAccountPanel.setPreferredSize(new java.awt.Dimension(600, 600));

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 20)); // NOI18N
        jLabel1.setText("Full Name             :");

        nameLabel.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(60, 60, 60));
        nameLabel.setText("Name");
        nameLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nameLabelMouseClicked(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(102, 102, 102));
        jLabel3.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 20)); // NOI18N
        jLabel3.setText("Address                 :");

        addressLabel.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        addressLabel.setForeground(new java.awt.Color(60, 60, 60));
        addressLabel.setText("Address");

        jLabel5.setBackground(new java.awt.Color(102, 102, 102));
        jLabel5.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 20)); // NOI18N
        jLabel5.setText("Date of Birth         :");

        dobLabel.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        dobLabel.setForeground(new java.awt.Color(60, 60, 60));
        dobLabel.setText("Date");

        jLabel7.setBackground(new java.awt.Color(102, 102, 102));
        jLabel7.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 20)); // NOI18N
        jLabel7.setText("Email                     :");

        emailLabel.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        emailLabel.setForeground(new java.awt.Color(60, 60, 60));
        emailLabel.setText("Email");

        passwordLabel.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(60, 60, 60));
        passwordLabel.setText("Password");

        jLabel12.setBackground(new java.awt.Color(102, 102, 102));
        jLabel12.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 20)); // NOI18N
        jLabel12.setText("Password              :");

        passwordToggleBtn.setText("show");
        passwordToggleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordToggleBtnActionPerformed(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(102, 102, 102));
        jLabel8.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 20)); // NOI18N
        jLabel8.setText("Username             :");

        usernameLabel.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(60, 60, 60));
        usernameLabel.setText("Username");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thehotelfinder/imgs/account.png"))); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(500, 500));

        jLabel4.setBackground(new java.awt.Color(245, 245, 245));
        jLabel4.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 255));
        jLabel4.setText("Account Details");

        javax.swing.GroupLayout MyAccountPanelLayout = new javax.swing.GroupLayout(MyAccountPanel);
        MyAccountPanel.setLayout(MyAccountPanelLayout);
        MyAccountPanelLayout.setHorizontalGroup(
            MyAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MyAccountPanelLayout.createSequentialGroup()
                .addGroup(MyAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MyAccountPanelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4))
                    .addGroup(MyAccountPanelLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(MyAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(MyAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameLabel)
                            .addComponent(usernameLabel)
                            .addGroup(MyAccountPanelLayout.createSequentialGroup()
                                .addComponent(passwordLabel)
                                .addGap(18, 18, 18)
                                .addComponent(passwordToggleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(dobLabel)
                            .addComponent(addressLabel)
                            .addComponent(emailLabel))))
                .addContainerGap(161, Short.MAX_VALUE))
        );
        MyAccountPanelLayout.setVerticalGroup(
            MyAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MyAccountPanelLayout.createSequentialGroup()
                .addGroup(MyAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MyAccountPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MyAccountPanelLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(MyAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MyAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dobLabel))
                .addGap(18, 18, 18)
                .addGroup(MyAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addressLabel))
                .addGap(18, 18, 18)
                .addGroup(MyAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailLabel))
                .addGap(18, 18, 18)
                .addGroup(MyAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameLabel))
                .addGap(18, 18, 18)
                .addGroup(MyAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordLabel)
                    .addComponent(passwordToggleBtn))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        getContentPane().add(MyAccountPanel, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passwordToggleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordToggleBtnActionPerformed
        // TODO add your handling code here:
        if(passwordToggleBtn.isSelected()){
            passwordToggleBtn.setText("hide");
            passwordLabel.setText(TheHotelFinder.getCurUser().getPassword());
        }else{
            passwordToggleBtn.setText("show");
            String asters = "";
            for(int i=0; i<TheHotelFinder.getCurUser().getPassword().length(); i++){
                asters+="*";
            }
            passwordLabel.setText(asters);
        }
    }//GEN-LAST:event_passwordToggleBtnActionPerformed

    private void nameLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameLabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_nameLabelMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MyAccountPanel;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JLabel dobLabel;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JOptionPane jOptionPane;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JToggleButton passwordToggleBtn;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
